#Migration resume state
#Thu Mar 26 13:21:12 ICT 2026
EMPLOYEES.offset=2
EMPLOYEE_AUDIT.done=true
DEPARTMENT.offset=2
DEPARTMENTS.offset=2
EMPLOYEE.done=true
EMPLOYEES.done=true
EMPLOYEE_AUDIT.offset=2
DEPARTMENTS.done=true
DEPARTMENT.done=true
EMPLOYEE.offset=2
