spring.application.name=migration-db-web

# PostgreSQL storage for reusable saved database credentials
# Example:
# credential.store.jdbc-url=jdbc:postgresql://localhost:5432/migration_db
# credential.store.username=postgres
# credential.store.password=postgres
credential.store.jdbc-url=jdbc:postgresql://localhost:5432/migration_db
credential.store.username=postgres
credential.store.password=admin123
