package org.example.migrationdbweb.migratetool;

import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class OracleDialect implements SqlDialect {

    @Override
    public String quoteIdentifier(String identifier) {
        return "\"" + identifier.toUpperCase(Locale.ROOT) + "\"";
    }

    @Override
    public String mapDataType(ColumnDefinition col) {
        String baseType;

        switch (col.getJdbcType()) {
            case Types.VARCHAR:
            case Types.NVARCHAR:
            case Types.CHAR:
                baseType = col.getSize() > 0 ? "VARCHAR2(" + col.getSize() + ")" : "VARCHAR2(4000)";
                break;
            case Types.INTEGER:
            case Types.SMALLINT:
            case Types.TINYINT:
                baseType = "NUMBER(10)";
                break;
            case Types.BIGINT:
                baseType = "NUMBER(19)";
                break;
            case Types.DECIMAL:
            case Types.NUMERIC:
            case Types.DOUBLE:
            case Types.FLOAT:
                baseType = "NUMBER";
                break;
            case Types.BOOLEAN:
            case Types.BIT:
                baseType = "NUMBER(1)"; // Oracle truyền thống dùng NUMBER(1) cho boolean
                break;
            case Types.DATE:
                baseType = "DATE";
                break;
            case Types.TIMESTAMP:
                baseType = "TIMESTAMP";
                break;
            case Types.BLOB:
            case Types.BINARY:
            case Types.VARBINARY:
                baseType = "BLOB";
                break;
            case Types.CLOB:
                baseType = "CLOB";
                break;
            default:
                baseType = "VARCHAR2(255)";
        }

        // Dùng BY DEFAULT đềEcho phép migrate giữ nguyên PK từ source.
        if (col.isAutoIncrement()) {
            return baseType + " GENERATED BY DEFAULT AS IDENTITY";
        }
        return baseType;
    }

    @Override
    public String buildCreateTableSql(TableDefinition table) {
        StringBuilder sql = new StringBuilder();
        // Oracle thường yêu cầu tên đối tượng viết hoa
        sql.append("CREATE TABLE ").append(quoteIdentifier(table.getTableName().toUpperCase())).append(" (\n");

        List<ColumnDefinition> columns = table.getColumns();
        for (int i = 0; i < columns.size(); i++) {
            ColumnDefinition col = columns.get(i);

            sql.append("    ").append(quoteIdentifier(col.getName().toUpperCase())).append(" ");
            sql.append(mapDataType(col));

            if (!col.isNullable() && !col.isAutoIncrement()) {
                sql.append(" NOT NULL");
            }

            if (i < columns.size() - 1) {
                sql.append(",\n");
            }
        }

        // Primary Key
        List<String> pks = table.getPrimaryKeys();
        if (!pks.isEmpty()) {
            sql.append(",\n    CONSTRAINT PK_").append(table.getTableName().toUpperCase()).append(" PRIMARY KEY (");
            for (int i = 0; i < pks.size(); i++) {
                sql.append(quoteIdentifier(pks.get(i).toUpperCase()));
                if (i < pks.size() - 1) sql.append(", ");
            }
            sql.append(")");
        }

        sql.append("\n)"); // Oracle không cần dấu ; trong statement thực thi qua JDBC
        return sql.toString();
    }
    @Override
    public List<String> buildAddForeignKeySql(TableDefinition table) {
        List<String> alterStatements = new ArrayList<>();

        for (ForeignKeyDefinition fk : table.getForeignKeys()) {
            StringBuilder sql = new StringBuilder();

            String constraintName = fk.getFkName();
            if (constraintName == null || constraintName.isEmpty()) {
                // Oracle giới hạn tên identifier max 30 ký tự (trước 12cR2), nên có thềEcần logic rút gọn tên ềEđây
                constraintName = "FK_" + table.getTableName() + "_" + fk.getFkColumnName();
            }

            // Oracle không cần dấu chấm phẩy ; nếu chạy qua JDBC PreparedStatement/Statement
            sql.append("ALTER TABLE ").append(quoteIdentifier(table.getTableName().toUpperCase())).append("\n");
            sql.append("    ADD CONSTRAINT ").append(quoteIdentifier(constraintName.toUpperCase())).append("\n");
            sql.append("    FOREIGN KEY (").append(quoteIdentifier(fk.getFkColumnName().toUpperCase())).append(")\n");
            sql.append("    REFERENCES ").append(quoteIdentifier(fk.getTargetTableName().toUpperCase()))
                    .append(" (").append(quoteIdentifier(fk.getTargetColumnName().toUpperCase())).append(")");

            alterStatements.add(sql.toString());
        }

        return alterStatements;
    }

    // ─── SEQUENCE DDL ───────────────────────────────────────────────

    @Override
    public String buildCreateSequenceSql(SequenceDefinition seq) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE SEQUENCE ");
        sb.append(quoteIdentifier(seq.getSequenceName()));
        if (seq.getStartValue() > 0) {
            sb.append(" START WITH ").append(seq.getStartValue());
        }
        if (seq.getIncrementBy() != 0) {
            sb.append(" INCREMENT BY ").append(seq.getIncrementBy());
        }
        if (seq.getMinValue() != null) {
            sb.append(" MINVALUE ").append(seq.getMinValue());
        }
        if (seq.getMaxValue() != null) {
            sb.append(" MAXVALUE ").append(seq.getMaxValue());
        }
        if (seq.getCacheSize() != null && seq.getCacheSize() > 1) {
            sb.append(" CACHE ").append(seq.getCacheSize());
        } else {
            sb.append(" NOCACHE");
        }
        sb.append(seq.isCycle() ? " CYCLE" : " NOCYCLE");
        return sb.toString();
    }

    @Override
    public List<String> buildCreateIndexSql(IndexDefinition idx) {
        List<String> stmts = new ArrayList<>();
        StringBuilder sb = new StringBuilder();

        // Oracle BITMAP index được migrate nhưng PostgreSQL không có BITMAP
        // → Vẫn tạo trên Oracle→Oracle, nhưng báo warning cho Oracle→PostgreSQL
        if (!idx.isMigratable() && idx.getIndexType() == IndexDefinition.IndexType.BITMAP) {
            // BITMAP index — Oracle only, migrate bằng cách tạo thành B-Tree
            System.err.println("WARN: BITMAP index " + idx.getIndexName()
                    + " cannot be migrated to PostgreSQL. Converting to B-Tree.");
        }

        sb.append(idx.isUnique() ? "CREATE UNIQUE INDEX " : "CREATE INDEX ");
        if (idx.getIndexName() != null) {
            sb.append(quoteIdentifier(idx.getIndexName())).append(" ");
        }
        sb.append("ON ").append(quoteIdentifier(idx.getTableName()));

        if (idx.isExpressionIndex() && idx.getExpression() != null) {
            sb.append(" (").append(idx.getExpression()).append(")");
        } else {
            appendIndexColumns(sb, idx);
        }

        if (idx.getTablespace() != null && !idx.getTablespace().isBlank()) {
            sb.append(" TABLESPACE ").append(idx.getTablespace());
        }

        stmts.add(sb.toString());
        return stmts;
    }

    private void appendIndexColumns(StringBuilder sb, IndexDefinition idx) {
        sb.append(" (");
        List<String> cols = idx.getColumns();
        List<String> descs = idx.getDescendings();
        for (int i = 0; i < cols.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(quoteIdentifier(cols.get(i)));
            if (descs != null && i < descs.size() && "DESC".equalsIgnoreCase(descs.get(i))) {
                sb.append(" DESC");
            }
        }
        sb.append(")");
    }

    // ─── TRIGGER DDL ───────────────────────────────────────────────

    @Override
    public List<String> buildCreateTriggerSql(TriggerDefinition trig, OracleToPgsqlTransformer transformer) {
        List<String> stmts = new ArrayList<>();
        if (trig == null) return stmts;

        String body = trig.getTriggerBody();
        if (body == null || body.isBlank()) {
            return stmts;
        }

        if (trig.getSourceDialect() == DatabaseType.POSTGRESQL) {
            body = new PostgresToOracleTransformer().transformTriggerBody(body);
            for (String warning : PostgresToOracleTransformer.detectUnsupportedFeatures(body)) {
                System.err.println("  [PG2ORA-TRIGGER-WARN] " + trig.getTriggerName() + ": " + warning);
            }
        }

        // Ưu tiên dùng DDL gốc đã lưu trong TriggerDefinition (từ MetadataExtractor)
        String ddl = trig.getDdlText();
        if (trig.getSourceDialect() == DatabaseType.POSTGRESQL || ddl == null || ddl.isBlank()) {
            // Fallback: build từ TriggerDefinition fields
            ddl = buildOracleTriggerFromDefinition(trig, body);
        } else {
            // DDL gốc có sẵn — chỉ replace schema nếu cần
            if (trig.getSourceSchema() != null && trig.getTargetSchema() != null
                    && !trig.getSourceSchema().equalsIgnoreCase(trig.getTargetSchema())) {
                ddl = remapSchemaPrefixSafely(ddl, trig.getSourceSchema(), trig.getTargetSchema());
            }
        }

        // Bỏ dấu ; cuối
        if (ddl.endsWith(";")) {
            ddl = ddl.substring(0, ddl.length() - 1);
        }

        stmts.add(ddl);
        return stmts;
    }

    /**
     * Lấy trigger DDL đầy đủ từ Oracle qua DBMS_METADATA.GET_DDL.
     *
     * DBMS_METADATA.GET_DDL trả về CLOB chứa câu lệnh CREATE TRIGGER hoàn chỉnh
     * bao gồm: CREATE [OR REPLACE] TRIGGER, timing, event, table, WHEN clause, body.
     *
     * @param schema       schema chứa trigger
     * @param triggerName  tên trigger
     * @return full CREATE TRIGGER DDL, hoặc null nếu không lấy được
     */
    private String extractOracleTriggerDdl(String schema, String triggerName) {
        // NOTE: vì OracleDialect không giữ Connection riêng,
        // việc lấy DDL gốc được thực hiện trong MetadataExtractor
        // và lưu vào TriggerDefinition.ddlText.
        // Method này hiện chỉ trả về null, dùng làm placeholder.
        return null;
    }

    /**
     * Build Oracle trigger DDL từ TriggerDefinition fields.
     * Dùng khi không lấy được full DDL từ Oracle metadata.
     */
    private String buildOracleTriggerFromDefinition(TriggerDefinition trig, String bodyText) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE OR REPLACE TRIGGER ");
        sb.append(quoteIdentifier(trig.getTriggerName()));
        sb.append("\n");

        // Timing
        if (trig.getTiming() != null) {
            sb.append(trig.getTiming().name().replace("_", " "));
            sb.append(" ");
        }

        // Event
        sb.append(trig.getTriggeringEvent());
        sb.append(" ON ");
        sb.append(quoteIdentifier(trig.getTableName()));

        // FOR EACH ROW
        if (trig.isRowLevel()) {
            sb.append("\nFOR EACH ROW");
        }

        // WHEN clause
        if (trig.hasWhenClause()) {
            sb.append("\nWHEN (").append(trig.getWhenClause()).append(")");
        }

        sb.append("\n");
        sb.append(bodyText);

        return sb.toString();
    }

    @Override
    public String buildCreateViewSql(ViewDefinition viewDef) {
        if (viewDef.getSourceDialect() == DatabaseType.POSTGRESQL) {
            String select = viewDef.getSelectClause();
            if (select == null || select.isBlank()) {
                return null;
            }

            select = select.trim();
            if (select.endsWith(";")) {
                select = select.substring(0, select.length() - 1);
            }

            PostgresToOracleTransformer transformer = new PostgresToOracleTransformer();
            select = transformer.transform(select);

            String sourceSchema = viewDef.getSourceSchema();
            String targetSchema = viewDef.getTargetSchema();
            if (sourceSchema != null && targetSchema != null
                    && !sourceSchema.equalsIgnoreCase(targetSchema)) {
                select = remapSchemaPrefixSafely(select, sourceSchema, targetSchema);
            }

            StringBuilder sql = new StringBuilder();
            sql.append("CREATE OR REPLACE VIEW ");
            sql.append(quoteIdentifier(viewDef.getViewName()));
            sql.append(" AS\n");
            sql.append(select);
            if (viewDef.getCheckOption() != null && !viewDef.getCheckOption().isBlank()) {
                sql.append("\nWITH ").append(viewDef.getCheckOption()).append(" CHECK OPTION");
            }
            return sql.toString();
        }

        // Oracle USER_VIEWS.TEXT chứa "CREATE [OR REPLACE] ... VIEW ... AS SELECT ..."
        // hoặc chỉ chứa SELECT clause tùy cách parse metadata.
        // Nếu chỉ là SELECT clause thì phải build lại CREATE OR REPLACE VIEW.
        String text = viewDef.getSelectClause();
        if (text == null || text.isBlank()) {
            return null;
        }
        text = text.trim();

        // Replace source schema bằng target schema nếu khác nhau
        String sourceSchema = viewDef.getSourceSchema();
        String targetSchema = viewDef.getTargetSchema();
        if (sourceSchema != null && targetSchema != null
                && !sourceSchema.equalsIgnoreCase(targetSchema)) {
            text = remapSchemaPrefixSafely(text, sourceSchema, targetSchema);
        }

        // Oracle TEXT có thể kết thúc bằng dấu ;
        if (text.endsWith(";")) {
            text = text.substring(0, text.length() - 1);
        }

        String upper = text.toUpperCase(Locale.ROOT);
        boolean looksLikeCreateView = upper.startsWith("CREATE ") && upper.contains(" VIEW ");
        if (looksLikeCreateView) {
            return text;
        }

        StringBuilder sql = new StringBuilder();
        sql.append("CREATE OR REPLACE VIEW ");
        sql.append(quoteIdentifier(viewDef.getViewName()));
        sql.append(" AS\n");
        sql.append(text);
        if (viewDef.getCheckOption() != null && !viewDef.getCheckOption().isBlank()) {
            sql.append("\nWITH ").append(viewDef.getCheckOption()).append(" CHECK OPTION");
        }
        return sql.toString();
    }

	// ─── FUNCTION / PROCEDURE DDL ──────────────────────────────

	@Override
	public List<String> buildCreateFunctionSql(FunctionDefinition fn, OracleToPgsqlTransformer transformer) {
		List<String> stmts = new ArrayList<>();
		if (fn == null) return stmts;

        if (fn.getSourceDialect() == DatabaseType.ORACLE
                && fn.getDdlText() != null && !fn.getDdlText().isBlank()) {
            String ddl = remapOracleSchemaPrefix(fn.getDdlText(), fn.getSourceSchema(), fn.getTargetSchema());
            ddl = stripSqlPlusDelimiter(ddl);
            if (ddl != null && !ddl.isBlank()) {
                stmts.add(ddl.trim());
                return stmts;
            }
        }

		String body = fn.getFunctionBody();
		if (body == null || body.isBlank()) {
			return stmts;
		}

        if (fn.getSourceDialect() == DatabaseType.POSTGRESQL) {
            PostgresToOracleTransformer pgTransformer = new PostgresToOracleTransformer();
            body = pgTransformer.transform(body);
            for (String warning : PostgresToOracleTransformer.detectUnsupportedFeatures(body)) {
                System.err.println("  [PG2ORA-FUNCTION-WARN] " + fn.getFunctionName() + ": " + warning);
            }
        } else if (fn.getSourceDialect() == DatabaseType.ORACLE) {
            body = stripOracleRoutineHeader(body);
        }

		StringBuilder sb = new StringBuilder();
		if (fn.isProcedure()) {
			sb.append("CREATE OR REPLACE PROCEDURE ");
		} else {
			sb.append("CREATE OR REPLACE FUNCTION ");
		}
		sb.append(quoteIdentifier(fn.getFunctionName()));
		sb.append("(");

		List<FunctionDefinition.FunctionArgument> args = fn.getArguments();
		for (int i = 0; i < args.size(); i++) {
			if (i > 0) sb.append(", ");
			FunctionDefinition.FunctionArgument arg = args.get(i);
            if (arg.getMode() != null) {
                switch (arg.getMode()) {
                    case OUT -> sb.append("OUT ");
                    case INOUT -> sb.append("IN OUT ");
                    default -> sb.append("IN ");
                }
            }
			if (arg.getName() != null && !arg.getName().isBlank()) {
                sb.append(arg.getName().toUpperCase(Locale.ROOT)).append(" ");
			}
            sb.append(mapPostgresTypeToOracle(arg.getDataType()));
		}
		sb.append(")");
		if (fn.isFunction() && fn.getReturnType() != null) {
            sb.append(" RETURN ").append(mapPostgresTypeToOracle(fn.getReturnType()));
        } else if (fn.isFunction()) {
            sb.append(" RETURN VARCHAR2");
		}
		sb.append(" AS\n");
		sb.append(body);
		if (!body.trim().endsWith("/")) {
			sb.append("\n/");
		}

		stmts.add(sb.toString());
		return stmts;
	}

    private static String remapOracleSchemaPrefix(String ddl, String sourceSchema, String targetSchema) {
        return remapSchemaPrefixSafely(ddl, sourceSchema, targetSchema);
    }

    public static String remapSchemaPrefixSafely(String text, String sourceSchema, String targetSchema) {
        if (text == null || text.isBlank()) {
            return text;
        }
        if (sourceSchema == null || sourceSchema.isBlank()
                || targetSchema == null || targetSchema.isBlank()
                || sourceSchema.equalsIgnoreCase(targetSchema)) {
            return text;
        }

        String source = sourceSchema.trim();
        String sourceUpper = source.toUpperCase(Locale.ROOT);
        String target = targetSchema.trim();

        StringBuilder out = new StringBuilder(text.length() + 32);
        int i = 0;
        boolean inSingleQuote = false;
        boolean inLineComment = false;
        boolean inBlockComment = false;

        while (i < text.length()) {
            char c = text.charAt(i);

            if (inLineComment) {
                out.append(c);
                i++;
                if (c == '\n') {
                    inLineComment = false;
                }
                continue;
            }

            if (inBlockComment) {
                out.append(c);
                i++;
                if (c == '*' && i < text.length() && text.charAt(i) == '/') {
                    out.append('/');
                    i++;
                    inBlockComment = false;
                }
                continue;
            }

            if (inSingleQuote) {
                out.append(c);
                i++;
                if (c == '\'' && i < text.length() && text.charAt(i) == '\'') {
                    out.append('\'');
                    i++;
                    continue;
                }
                if (c == '\'') {
                    inSingleQuote = false;
                }
                continue;
            }

            if (c == '\'') {
                inSingleQuote = true;
                out.append(c);
                i++;
                continue;
            }

            if (c == '-' && i + 1 < text.length() && text.charAt(i + 1) == '-') {
                inLineComment = true;
                out.append("--");
                i += 2;
                continue;
            }

            if (c == '/' && i + 1 < text.length() && text.charAt(i + 1) == '*') {
                inBlockComment = true;
                out.append("/*");
                i += 2;
                continue;
            }

            Match match = matchSchemaPrefix(text, i, sourceUpper, target);
            if (match != null) {
                out.append(match.replacement);
                i = match.nextIndex;
                continue;
            }

            out.append(c);
            i++;
        }

        return out.toString();
    }

    private static Match matchSchemaPrefix(String text, int start, String sourceUpper, String targetSchema) {
        Match quoted = matchQuotedSchemaPrefix(text, start, sourceUpper, targetSchema);
        if (quoted != null) {
            return quoted;
        }
        return matchUnquotedSchemaPrefix(text, start, sourceUpper, targetSchema);
    }

    private static Match matchQuotedSchemaPrefix(String text, int start, String sourceUpper, String targetSchema) {
        if (start >= text.length() || text.charAt(start) != '"') {
            return null;
        }

        int endQuote = findClosingQuote(text, start + 1);
        if (endQuote < 0) {
            return null;
        }

        String identifier = text.substring(start + 1, endQuote);
        if (!identifier.equalsIgnoreCase(sourceUpper)) {
            return null;
        }

        int pos = endQuote + 1;
        while (pos < text.length() && Character.isWhitespace(text.charAt(pos))) {
            pos++;
        }
        if (pos >= text.length() || text.charAt(pos) != '.') {
            return null;
        }
        pos++;
        while (pos < text.length() && Character.isWhitespace(text.charAt(pos))) {
            pos++;
        }

        return new Match(pos, "\"" + targetSchema.toUpperCase(Locale.ROOT) + "\".");
    }

    private static int findClosingQuote(String text, int start) {
        int i = start;
        while (i < text.length()) {
            char c = text.charAt(i);
            if (c == '"') {
                if (i + 1 < text.length() && text.charAt(i + 1) == '"') {
                    i += 2;
                    continue;
                }
                return i;
            }
            i++;
        }
        return -1;
    }

    private static Match matchUnquotedSchemaPrefix(String text, int start, String sourceUpper, String targetSchema) {
        int len = sourceUpper.length();
        if (start + len > text.length()) {
            return null;
        }

        if (!text.regionMatches(true, start, sourceUpper, 0, len)) {
            return null;
        }

        int before = start - 1;
        if (before >= 0 && isIdentifierChar(text.charAt(before))) {
            return null;
        }

        int pos = start + len;
        if (pos < text.length() && isIdentifierChar(text.charAt(pos))) {
            return null;
        }

        while (pos < text.length() && Character.isWhitespace(text.charAt(pos))) {
            pos++;
        }
        if (pos >= text.length() || text.charAt(pos) != '.') {
            return null;
        }
        pos++;
        while (pos < text.length() && Character.isWhitespace(text.charAt(pos))) {
            pos++;
        }

        return new Match(pos, targetSchema + ".");
    }

    private static boolean isIdentifierChar(char c) {
        return Character.isLetterOrDigit(c) || c == '_' || c == '$' || c == '#';
    }

    private static final class Match {
        private final int nextIndex;
        private final String replacement;

        private Match(int nextIndex, String replacement) {
            this.nextIndex = nextIndex;
            this.replacement = replacement;
        }
    }

    private static String stripSqlPlusDelimiter(String ddl) {
        if (ddl == null) {
            return null;
        }
        String normalized = ddl.trim();
        if (normalized.endsWith("/")) {
            normalized = normalized.substring(0, normalized.length() - 1).trim();
        }
        return normalized;
    }

    private static String stripOracleRoutineHeader(String body) {
        if (body == null || body.isBlank()) {
            return body;
        }

        String trimmed = body.trim();
        int delimiterPos = findHeaderBodyDelimiter(trimmed);
        if (delimiterPos < 0) {
            return trimmed;
        }

        String afterDelimiter = trimmed.substring(delimiterPos + 2).trim();
        if (afterDelimiter.startsWith(";")) {
            afterDelimiter = afterDelimiter.substring(1).trim();
        }
        return afterDelimiter;
    }

    private static int findHeaderBodyDelimiter(String text) {
        int len = text.length();
        boolean inString = false;

        for (int i = 0; i <= len - 2; i++) {
            char current = text.charAt(i);
            if (current == '\'') {
                if (inString && i + 1 < len && text.charAt(i + 1) == '\'') {
                    i++;
                    continue;
                }
                inString = !inString;
                continue;
            }

            if (inString) {
                continue;
            }

            if (text.regionMatches(true, i, "AS", 0, 2) || text.regionMatches(true, i, "IS", 0, 2)) {
                int before = i - 1;
                int after = i + 2;
                boolean validBefore = before < 0 || !Character.isLetterOrDigit(text.charAt(before)) && text.charAt(before) != '_';
                boolean validAfter = after >= len || !Character.isLetterOrDigit(text.charAt(after)) && text.charAt(after) != '_';
                if (validBefore && validAfter) {
                    return i;
                }
            }
        }

        return -1;
    }

    private static String mapPostgresTypeToOracle(String dataType) {
        if (dataType == null || dataType.isBlank()) {
            return "VARCHAR2";
        }

        String normalized = dataType.trim().toLowerCase(Locale.ROOT);
        if (normalized.startsWith("character varying") || normalized.startsWith("varchar")) {
            java.util.regex.Matcher m = java.util.regex.Pattern
                    .compile(".*\\((\\d+)\\)")
                    .matcher(normalized);
            if (m.matches()) {
                return "VARCHAR2(" + m.group(1) + ")";
            }
            return "VARCHAR2";
        }
        if (normalized.startsWith("character") || normalized.startsWith("char")) {
            java.util.regex.Matcher m = java.util.regex.Pattern
                    .compile(".*\\((\\d+)\\)")
                    .matcher(normalized);
            if (m.matches()) {
                return "CHAR(" + m.group(1) + ")";
            }
            return "CHAR(1)";
        }
        if (normalized.equals("text")) return "CLOB";
        if (normalized.equals("smallint") || normalized.equals("int2")) return "NUMBER(5)";
        if (normalized.equals("integer") || normalized.equals("int") || normalized.equals("int4")) return "NUMBER(10)";
        if (normalized.equals("bigint") || normalized.equals("int8")) return "NUMBER(19)";
        if (normalized.equals("numeric") || normalized.equals("decimal")) return "NUMBER";
        if (normalized.equals("real") || normalized.equals("float4")) return "BINARY_FLOAT";
        if (normalized.equals("double precision") || normalized.equals("float8")) return "BINARY_DOUBLE";
        if (normalized.equals("boolean") || normalized.equals("bool")) return "NUMBER(1)";
        if (normalized.equals("date")) return "DATE";
        if (normalized.startsWith("timestamp")) return "TIMESTAMP";
        if (normalized.equals("bytea")) return "BLOB";
        if (normalized.equals("json") || normalized.equals("jsonb")) return "CLOB";
        if (normalized.equals("uuid")) return "VARCHAR2(36)";

        return dataType;
    }
	}
