package org.example.migrationdbweb.migratetool;

import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;

public class OracleDialect implements SqlDialect {

    @Override
    public String quoteIdentifier(String identifier) {
        return "\"" + identifier.toUpperCase(Locale.ROOT) + "\"";
    }

    @Override
    public String mapDataType(ColumnDefinition col) {
        String baseType;

        switch (col.getJdbcType()) {
            case Types.VARCHAR:
            case Types.NVARCHAR:
            case Types.CHAR:
                baseType = col.getSize() > 0 ? "VARCHAR2(" + col.getSize() + ")" : "VARCHAR2(4000)";
                break;
            case Types.INTEGER:
            case Types.SMALLINT:
            case Types.TINYINT:
                baseType = "NUMBER(10)";
                break;
            case Types.BIGINT:
                baseType = "NUMBER(19)";
                break;
            case Types.DECIMAL:
            case Types.NUMERIC:
            case Types.DOUBLE:
            case Types.FLOAT:
                baseType = "NUMBER";
                break;
            case Types.BOOLEAN:
            case Types.BIT:
                baseType = "NUMBER(1)"; // Oracle truyền thống dùng NUMBER(1) cho boolean
                break;
            case Types.DATE:
                baseType = "DATE";
                break;
            case Types.TIMESTAMP:
                baseType = "TIMESTAMP";
                break;
            case Types.BLOB:
            case Types.BINARY:
            case Types.VARBINARY:
                baseType = "BLOB";
                break;
            case Types.CLOB:
                baseType = "CLOB";
                break;
            default:
                baseType = "VARCHAR2(255)";
        }

        // Dùng BY DEFAULT đềEcho phép migrate giữ nguyên PK từ source.
        if (col.isAutoIncrement()) {
            return baseType + " GENERATED BY DEFAULT AS IDENTITY";
        }
        return baseType;
    }

    @Override
    public String buildCreateTableSql(TableDefinition table) {
        StringBuilder sql = new StringBuilder();
        // Oracle thường yêu cầu tên đối tượng viết hoa
        sql.append("CREATE TABLE ").append(quoteIdentifier(table.getTableName().toUpperCase())).append(" (\n");

        List<ColumnDefinition> columns = table.getColumns();
        for (int i = 0; i < columns.size(); i++) {
            ColumnDefinition col = columns.get(i);

            sql.append("    ").append(quoteIdentifier(col.getName().toUpperCase())).append(" ");
            sql.append(mapDataType(col));

            if (!col.isNullable() && !col.isAutoIncrement()) {
                sql.append(" NOT NULL");
            }

            if (i < columns.size() - 1) {
                sql.append(",\n");
            }
        }

        // Primary Key
        List<String> pks = table.getPrimaryKeys();
        if (!pks.isEmpty()) {
            sql.append(",\n    CONSTRAINT PK_").append(table.getTableName().toUpperCase()).append(" PRIMARY KEY (");
            for (int i = 0; i < pks.size(); i++) {
                sql.append(quoteIdentifier(pks.get(i).toUpperCase()));
                if (i < pks.size() - 1) sql.append(", ");
            }
            sql.append(")");
        }

        sql.append("\n)"); // Oracle không cần dấu ; trong statement thực thi qua JDBC
        return sql.toString();
    }
    @Override
    public List<String> buildAddForeignKeySql(TableDefinition table) {
        List<String> alterStatements = new ArrayList<>();

        for (ForeignKeyDefinition fk : table.getForeignKeys()) {
            StringBuilder sql = new StringBuilder();

            String constraintName = fk.getFkName();
            if (constraintName == null || constraintName.isEmpty()) {
                // Oracle giới hạn tên identifier max 30 ký tự (trước 12cR2), nên có thềEcần logic rút gọn tên ềEđây
                constraintName = "FK_" + table.getTableName() + "_" + fk.getFkColumnName();
            }

            // Oracle không cần dấu chấm phẩy ; nếu chạy qua JDBC PreparedStatement/Statement
            sql.append("ALTER TABLE ").append(quoteIdentifier(table.getTableName().toUpperCase())).append("\n");
            sql.append("    ADD CONSTRAINT ").append(quoteIdentifier(constraintName.toUpperCase())).append("\n");
            sql.append("    FOREIGN KEY (").append(quoteIdentifier(fk.getFkColumnName().toUpperCase())).append(")\n");
            sql.append("    REFERENCES ").append(quoteIdentifier(fk.getTargetTableName().toUpperCase()))
                    .append(" (").append(quoteIdentifier(fk.getTargetColumnName().toUpperCase())).append(")");

            alterStatements.add(sql.toString());
        }

        return alterStatements;
    }

    // ─── SEQUENCE DDL ───────────────────────────────────────────────

    @Override
    public String buildCreateSequenceSql(SequenceDefinition seq) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE SEQUENCE ");
        sb.append(quoteIdentifier(seq.getSequenceName()));
        if (seq.getStartValue() > 0) {
            sb.append(" START WITH ").append(seq.getStartValue());
        }
        if (seq.getIncrementBy() != 0) {
            sb.append(" INCREMENT BY ").append(seq.getIncrementBy());
        }
        if (seq.getMinValue() != null) {
            sb.append(" MINVALUE ").append(seq.getMinValue());
        }
        if (seq.getMaxValue() != null) {
            sb.append(" MAXVALUE ").append(seq.getMaxValue());
        }
        if (seq.getCacheSize() != null && seq.getCacheSize() > 1) {
            sb.append(" CACHE ").append(seq.getCacheSize());
        } else {
            sb.append(" NOCACHE");
        }
        sb.append(seq.isCycle() ? " CYCLE" : " NOCYCLE");
        return sb.toString();
    }

    @Override
    public List<String> buildCreateIndexSql(IndexDefinition idx) {
        List<String> stmts = new ArrayList<>();
        StringBuilder sb = new StringBuilder();

        // Oracle BITMAP index được migrate nhưng PostgreSQL không có BITMAP
        // → Vẫn tạo trên Oracle→Oracle, nhưng báo warning cho Oracle→PostgreSQL
        if (!idx.isMigratable() && idx.getIndexType() == IndexDefinition.IndexType.BITMAP) {
            // BITMAP index — Oracle only, migrate bằng cách tạo thành B-Tree
            System.err.println("WARN: BITMAP index " + idx.getIndexName()
                    + " cannot be migrated to PostgreSQL. Converting to B-Tree.");
        }

        sb.append(idx.isUnique() ? "CREATE UNIQUE INDEX " : "CREATE INDEX ");
        if (idx.getIndexName() != null) {
            sb.append(quoteIdentifier(idx.getIndexName())).append(" ");
        }
        sb.append("ON ").append(quoteIdentifier(idx.getTableName()));

        if (idx.isExpressionIndex() && idx.getExpression() != null) {
            sb.append(" (").append(idx.getExpression()).append(")");
        } else {
            appendIndexColumns(sb, idx);
        }

        if (idx.getTablespace() != null && !idx.getTablespace().isBlank()) {
            sb.append(" TABLESPACE ").append(idx.getTablespace());
        }

        stmts.add(sb.toString());
        return stmts;
    }

    private void appendIndexColumns(StringBuilder sb, IndexDefinition idx) {
        sb.append(" (");
        List<String> cols = idx.getColumns();
        List<String> descs = idx.getDescendings();
        for (int i = 0; i < cols.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(quoteIdentifier(cols.get(i)));
            if (descs != null && i < descs.size() && "DESC".equalsIgnoreCase(descs.get(i))) {
                sb.append(" DESC");
            }
        }
        sb.append(")");
    }

    // ─── TRIGGER DDL ───────────────────────────────────────────────

    @Override
    public List<String> buildCreateTriggerSql(TriggerDefinition trig, OracleToPgsqlTransformer transformer) {
        List<String> stmts = new ArrayList<>();
        if (trig == null) return stmts;

        String body = trig.getTriggerBody();
        if (body == null || body.isBlank()) {
            return stmts;
        }

        if (trig.getSourceDialect() == DatabaseType.POSTGRESQL) {
            body = new PostgresToOracleTransformer().transformTriggerBody(body);
            for (String warning : PostgresToOracleTransformer.detectUnsupportedFeatures(body)) {
                System.err.println("  [PG2ORA-TRIGGER-WARN] " + trig.getTriggerName() + ": " + warning);
            }
        }

        // Ưu tiên dùng DDL gốc đã lưu trong TriggerDefinition (từ MetadataExtractor)
        String ddl = trig.getDdlText();
        if (trig.getSourceDialect() == DatabaseType.POSTGRESQL || ddl == null || ddl.isBlank()) {
            // Fallback: build từ TriggerDefinition fields
            ddl = buildOracleTriggerFromDefinition(trig, body);
        } else {
            // DDL gốc có sẵn — chỉ replace schema nếu cần
            if (trig.getSourceSchema() != null && trig.getTargetSchema() != null
                    && !trig.getSourceSchema().equalsIgnoreCase(trig.getTargetSchema())) {
                ddl = ddl.replaceAll(
                        "(?i)" + Pattern.quote(trig.getSourceSchema()) + "\\.",
                        trig.getTargetSchema() + "."
                );
            }
        }

        // Bỏ dấu ; cuối
        if (ddl.endsWith(";")) {
            ddl = ddl.substring(0, ddl.length() - 1);
        }

        stmts.add(ddl);
        return stmts;
    }

    /**
     * Lấy trigger DDL đầy đủ từ Oracle qua DBMS_METADATA.GET_DDL.
     *
     * DBMS_METADATA.GET_DDL trả về CLOB chứa câu lệnh CREATE TRIGGER hoàn chỉnh
     * bao gồm: CREATE [OR REPLACE] TRIGGER, timing, event, table, WHEN clause, body.
     *
     * @param schema       schema chứa trigger
     * @param triggerName  tên trigger
     * @return full CREATE TRIGGER DDL, hoặc null nếu không lấy được
     */
    private String extractOracleTriggerDdl(String schema, String triggerName) {
        // NOTE: vì OracleDialect không giữ Connection riêng,
        // việc lấy DDL gốc được thực hiện trong MetadataExtractor
        // và lưu vào TriggerDefinition.ddlText.
        // Method này hiện chỉ trả về null, dùng làm placeholder.
        return null;
    }

    /**
     * Build Oracle trigger DDL từ TriggerDefinition fields.
     * Dùng khi không lấy được full DDL từ Oracle metadata.
     */
    private String buildOracleTriggerFromDefinition(TriggerDefinition trig, String bodyText) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE OR REPLACE TRIGGER ");
        sb.append(quoteIdentifier(trig.getTriggerName()));
        sb.append("\n");

        // Timing
        if (trig.getTiming() != null) {
            sb.append(trig.getTiming().name().replace("_", " "));
            sb.append(" ");
        }

        // Event
        sb.append(trig.getTriggeringEvent());
        sb.append(" ON ");
        sb.append(quoteIdentifier(trig.getTableName()));

        // FOR EACH ROW
        if (trig.isRowLevel()) {
            sb.append("\nFOR EACH ROW");
        }

        // WHEN clause
        if (trig.hasWhenClause()) {
            sb.append("\nWHEN (").append(trig.getWhenClause()).append(")");
        }

        sb.append("\n");
        sb.append(bodyText);

        return sb.toString();
    }

    @Override
    public String buildCreateViewSql(ViewDefinition viewDef) {
        if (viewDef.getSourceDialect() == DatabaseType.POSTGRESQL) {
            String select = viewDef.getSelectClause();
            if (select == null || select.isBlank()) {
                return null;
            }

            select = select.trim();
            if (select.endsWith(";")) {
                select = select.substring(0, select.length() - 1);
            }

            PostgresToOracleTransformer transformer = new PostgresToOracleTransformer();
            select = transformer.transform(select);

            String sourceSchema = viewDef.getSourceSchema();
            String targetSchema = viewDef.getTargetSchema();
            if (sourceSchema != null && targetSchema != null
                    && !sourceSchema.equalsIgnoreCase(targetSchema)) {
                select = select.replaceAll(
                        "(?i)" + Pattern.quote(sourceSchema) + "\\.",
                        targetSchema + "."
                );
            }

            StringBuilder sql = new StringBuilder();
            sql.append("CREATE OR REPLACE VIEW ");
            sql.append(quoteIdentifier(viewDef.getViewName()));
            sql.append(" AS\n");
            sql.append(select);
            if (viewDef.getCheckOption() != null && !viewDef.getCheckOption().isBlank()) {
                sql.append("\nWITH ").append(viewDef.getCheckOption()).append(" CHECK OPTION");
            }
            return sql.toString();
        }

        // Oracle USER_VIEWS.TEXT chứa "CREATE [OR REPLACE] ... VIEW ... AS SELECT ..."
        // Đã là DDL đầy đủ, chỉ cần xử lý schema replacement + cleanup
        String text = viewDef.getSelectClause();
        if (text == null || text.isBlank()) {
            return null;
        }
        text = text.trim();

        // Replace source schema bằng target schema nếu khác nhau
        String sourceSchema = viewDef.getSourceSchema();
        String targetSchema = viewDef.getTargetSchema();
        if (sourceSchema != null && targetSchema != null
                && !sourceSchema.equalsIgnoreCase(targetSchema)) {
            // Replace "SOURCE_SCHEMA." thành "TARGET_SCHEMA."
            text = text.replaceAll(
                    "(?i)" + Pattern.quote(sourceSchema) + "\\.",
                    targetSchema + "."
            );
        }

        // Oracle TEXT có thể kết thúc bằng dấu ;
        if (text.endsWith(";")) {
            text = text.substring(0, text.length() - 1);
        }

        return text;
    }

	// ─── FUNCTION / PROCEDURE DDL ──────────────────────────────

	@Override
	public List<String> buildCreateFunctionSql(FunctionDefinition fn, OracleToPgsqlTransformer transformer) {
		List<String> stmts = new ArrayList<>();
		if (fn == null) return stmts;

		String body = fn.getFunctionBody();
		if (body == null || body.isBlank()) {
			return stmts;
		}

        if (fn.getSourceDialect() == DatabaseType.POSTGRESQL) {
            PostgresToOracleTransformer pgTransformer = new PostgresToOracleTransformer();
            body = pgTransformer.transform(body);
            for (String warning : PostgresToOracleTransformer.detectUnsupportedFeatures(body)) {
                System.err.println("  [PG2ORA-FUNCTION-WARN] " + fn.getFunctionName() + ": " + warning);
            }
        }

		StringBuilder sb = new StringBuilder();
		if (fn.isProcedure()) {
			sb.append("CREATE OR REPLACE PROCEDURE ");
		} else {
			sb.append("CREATE OR REPLACE FUNCTION ");
		}
		sb.append(quoteIdentifier(fn.getFunctionName()));
		sb.append("(");

		List<FunctionDefinition.FunctionArgument> args = fn.getArguments();
		for (int i = 0; i < args.size(); i++) {
			if (i > 0) sb.append(", ");
			FunctionDefinition.FunctionArgument arg = args.get(i);
            if (arg.getMode() != null) {
                switch (arg.getMode()) {
                    case OUT -> sb.append("OUT ");
                    case INOUT -> sb.append("IN OUT ");
                    default -> sb.append("IN ");
                }
            }
			if (arg.getName() != null && !arg.getName().isBlank()) {
                sb.append(arg.getName().toUpperCase(Locale.ROOT)).append(" ");
			}
            sb.append(mapPostgresTypeToOracle(arg.getDataType()));
		}
		sb.append(")");
		if (fn.isFunction() && fn.getReturnType() != null) {
            sb.append(" RETURN ").append(mapPostgresTypeToOracle(fn.getReturnType()));
        } else if (fn.isFunction()) {
            sb.append(" RETURN VARCHAR2");
		}
		sb.append(" AS\n");
		sb.append(body);
		if (!body.trim().endsWith("/")) {
			sb.append("\n/");
		}

		stmts.add(sb.toString());
		return stmts;
	}

    private static String mapPostgresTypeToOracle(String dataType) {
        if (dataType == null || dataType.isBlank()) {
            return "VARCHAR2";
        }

        String normalized = dataType.trim().toLowerCase(Locale.ROOT);
        if (normalized.startsWith("character varying") || normalized.startsWith("varchar")) {
            java.util.regex.Matcher m = java.util.regex.Pattern
                    .compile(".*\\((\\d+)\\)")
                    .matcher(normalized);
            if (m.matches()) {
                return "VARCHAR2(" + m.group(1) + ")";
            }
            return "VARCHAR2";
        }
        if (normalized.startsWith("character") || normalized.startsWith("char")) {
            java.util.regex.Matcher m = java.util.regex.Pattern
                    .compile(".*\\((\\d+)\\)")
                    .matcher(normalized);
            if (m.matches()) {
                return "CHAR(" + m.group(1) + ")";
            }
            return "CHAR(1)";
        }
        if (normalized.equals("text")) return "CLOB";
        if (normalized.equals("smallint") || normalized.equals("int2")) return "NUMBER(5)";
        if (normalized.equals("integer") || normalized.equals("int") || normalized.equals("int4")) return "NUMBER(10)";
        if (normalized.equals("bigint") || normalized.equals("int8")) return "NUMBER(19)";
        if (normalized.equals("numeric") || normalized.equals("decimal")) return "NUMBER";
        if (normalized.equals("real") || normalized.equals("float4")) return "BINARY_FLOAT";
        if (normalized.equals("double precision") || normalized.equals("float8")) return "BINARY_DOUBLE";
        if (normalized.equals("boolean") || normalized.equals("bool")) return "NUMBER(1)";
        if (normalized.equals("date")) return "DATE";
        if (normalized.startsWith("timestamp")) return "TIMESTAMP";
        if (normalized.equals("bytea")) return "BLOB";
        if (normalized.equals("json") || normalized.equals("jsonb")) return "CLOB";
        if (normalized.equals("uuid")) return "VARCHAR2(36)";

        return dataType;
    }
	}
