-- ============================================================================
-- Script tao du lieu test cho PostgreSQL Database
-- Schema: scott
-- ============================================================================

-- Tao schema neu chua ton tai
CREATE SCHEMA IF NOT EXISTS scott;

-- Xoa objects cu (neu co)
DROP VIEW IF EXISTS scott.v_customer_orders;
DROP VIEW IF EXISTS scott.v_product_summary;

DROP PROCEDURE IF EXISTS scott.get_employee_count(VARCHAR, BIGINT, VARCHAR);
DROP PROCEDURE IF EXISTS scott.update_order_status(NUMERIC, VARCHAR);

DROP FUNCTION IF EXISTS scott.calculate_order_total(NUMERIC);
DROP FUNCTION IF EXISTS scott.get_customer_level(NUMERIC);

DROP TABLE IF EXISTS scott.order_items CASCADE;
DROP TABLE IF EXISTS scott.orders CASCADE;
DROP TABLE IF EXISTS scott.products CASCADE;
DROP TABLE IF EXISTS scott.customers CASCADE;

-- ============================================================================
-- 1. TABLES
-- ============================================================================

CREATE TABLE scott.customers (
    customer_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name  VARCHAR(100) NOT NULL,
    email          VARCHAR(150),
    city           VARCHAR(50),
    country        VARCHAR(50) DEFAULT 'Vietnam',
    created_at     DATE DEFAULT CURRENT_DATE,
    status         VARCHAR(20) DEFAULT 'ACTIVE'
);

CREATE TABLE scott.products (
    product_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name   VARCHAR(200) NOT NULL,
    category       VARCHAR(50),
    price          NUMERIC(12, 2) NOT NULL,
    stock          NUMERIC(10) DEFAULT 0,
    created_at     DATE DEFAULT CURRENT_DATE
);

CREATE TABLE scott.orders (
    order_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT NOT NULL,
    order_date     DATE DEFAULT CURRENT_DATE,
    total_amount   NUMERIC(14, 2) DEFAULT 0,
    status         VARCHAR(30) DEFAULT 'PENDING',
    shipping_city  VARCHAR(50)
);

CREATE TABLE scott.order_items (
    item_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL,
    product_id     BIGINT NOT NULL,
    quantity       NUMERIC(5) NOT NULL,
    unit_price     NUMERIC(12, 2) NOT NULL,
    discount_pct   NUMERIC(5, 2) DEFAULT 0
);

-- Foreign Keys
ALTER TABLE scott.orders
    ADD CONSTRAINT fk_orders_customer
    FOREIGN KEY (customer_id) REFERENCES scott.customers(customer_id);

ALTER TABLE scott.order_items
    ADD CONSTRAINT fk_items_order
    FOREIGN KEY (order_id) REFERENCES scott.orders(order_id);

ALTER TABLE scott.order_items
    ADD CONSTRAINT fk_items_product
    FOREIGN KEY (product_id) REFERENCES scott.products(product_id);

-- ============================================================================
-- 2. DATA MAU
-- ============================================================================

-- Customers
INSERT INTO scott.customers (customer_name, email, city, country, status) VALUES
('Nguyen Van A', 'a.nguyen@email.com', 'Ho Chi Minh', 'Vietnam', 'ACTIVE'),
('Tran Thi B',   'b.tran@email.com',   'Ha Noi',      'Vietnam', 'ACTIVE'),
('Le Van C',     'c.le@email.com',     'Da Nang',     'Vietnam', 'INACTIVE'),
('Pham Thi D',   'd.pham@email.com',   'Can Tho',     'Vietnam', 'ACTIVE'),
('Hoang Van E',  'e.hoang@email.com',  'Hue',         'Vietnam', 'SUSPENDED');

-- Products
INSERT INTO scott.products (product_name, category, price, stock) VALUES
('Laptop Dell XPS 15',   'Electronics', 35000000, 25),
('iPhone 15 Pro',        'Electronics', 28000000, 50),
('Samsung Galaxy S24',   'Electronics', 22000000, 40),
('iPad Air M2',          'Electronics', 15000000, 30),
('MacBook Pro 14',       'Electronics', 42000000, 15),
('Sony WH-1000XM5',      'Accessories',  8500000, 60),
('AirPods Pro 2',        'Accessories',  5500000, 80),
('Apple Watch Ultra 2',  'Accessories', 18500000, 20);

-- Orders
INSERT INTO scott.orders (customer_id, order_date, total_amount, status, shipping_city) VALUES
(1, CURRENT_DATE - INTERVAL '10 day', 63000000, 'DELIVERED', 'Ho Chi Minh'),
(2, CURRENT_DATE - INTERVAL '7 day',  35000000, 'SHIPPED',   'Ha Noi'),
(1, CURRENT_DATE - INTERVAL '3 day',  15000000, 'CONFIRMED', 'Ho Chi Minh'),
(4, CURRENT_DATE - INTERVAL '1 day',  28000000, 'PENDING',   'Can Tho'),
(2, CURRENT_DATE,                      22000000, 'PENDING',   'Ha Noi');

-- Order Items
INSERT INTO scott.order_items (order_id, product_id, quantity, unit_price, discount_pct) VALUES
(1, 1, 1, 35000000,  0),
(1, 6, 1,  8500000,  5),
(1, 7, 2,  5500000,  0),
(2, 2, 1, 28000000, 10),
(3, 4, 1, 15000000,  0),
(4, 3, 1, 22000000,  0),
(5, 5, 1, 42000000,  0);

-- Update total_amount
UPDATE scott.orders o
SET total_amount = x.total_value
FROM (
    SELECT
        oi.order_id,
        COALESCE(SUM(oi.quantity * oi.unit_price * (1 - COALESCE(oi.discount_pct, 0) / 100)), 0) AS total_value
    FROM scott.order_items oi
    GROUP BY oi.order_id
) x
WHERE x.order_id = o.order_id;

-- ============================================================================
-- 3. VIEWS
-- ============================================================================

-- View 1: Thong tin khach hang + so don hang + tong tien
CREATE OR REPLACE VIEW scott.v_customer_orders AS
SELECT
    c.customer_id,
    c.customer_name,
    c.city,
    c.country,
    c.status,
    COUNT(o.order_id)                           AS total_orders,
    COALESCE(SUM(o.total_amount), 0)            AS total_spent,
    COALESCE(AVG(o.total_amount), 0)            AS avg_order_value,
    COALESCE(MAX(o.total_amount), 0)            AS max_order_value
FROM scott.customers c
LEFT JOIN scott.orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name, c.city, c.country, c.status;

-- View 2: Tom tat san pham + doanh thu + ton kho
CREATE OR REPLACE VIEW scott.v_product_summary AS
SELECT
    p.product_id,
    p.product_name,
    p.category,
    p.price,
    p.stock,
    COALESCE(SUM(oi.quantity), 0) AS total_sold,
    COALESCE(SUM(oi.quantity * oi.unit_price * (1 - COALESCE(oi.discount_pct, 0) / 100)), 0) AS total_revenue
FROM scott.products p
LEFT JOIN scott.order_items oi ON p.product_id = oi.product_id
LEFT JOIN scott.orders o ON oi.order_id = o.order_id
GROUP BY p.product_id, p.product_name, p.category, p.price, p.stock;

-- ============================================================================
-- 4. FUNCTIONS
-- ============================================================================

-- Function 1: Tinh cap bac khach hang
CREATE OR REPLACE FUNCTION scott.get_customer_level(p_customer_id IN NUMERIC)
RETURNS VARCHAR(20)
LANGUAGE plpgsql
AS $$
DECLARE
    v_total NUMERIC;
    v_level VARCHAR(20);
BEGIN
    SELECT COALESCE(SUM(total_amount), 0)
    INTO v_total
    FROM scott.orders
    WHERE customer_id = p_customer_id AND status <> 'CANCELLED';

    IF v_total >= 50000000 THEN
        v_level := 'GOLD';
    ELSIF v_total >= 20000000 THEN
        v_level := 'SILVER';
    ELSIF v_total >= 5000000 THEN
        v_level := 'BRONZE';
    ELSE
        v_level := 'NEW';
    END IF;

    RETURN v_level;
END;
$$;

-- Function 2: Tinh tong tien don hang (co discount)
CREATE OR REPLACE FUNCTION scott.calculate_order_total(p_order_id IN NUMERIC)
RETURNS NUMERIC
LANGUAGE plpgsql
AS $$
DECLARE
    v_total NUMERIC := 0;
BEGIN
    SELECT COALESCE(SUM(quantity * unit_price * (1 - COALESCE(discount_pct, 0) / 100)), 0)
    INTO v_total
    FROM scott.order_items
    WHERE order_id = p_order_id;

    RETURN ROUND(v_total, 2);
END;
$$;

-- ============================================================================
-- 5. PROCEDURES
-- ============================================================================

-- Procedure 1: Cap nhat trang thai don hang
CREATE OR REPLACE PROCEDURE scott.update_order_status(
    IN p_order_id NUMERIC,
    IN p_new_status VARCHAR
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_old_status VARCHAR(30);
BEGIN
    IF p_new_status NOT IN ('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED') THEN
        RAISE EXCEPTION 'Invalid status: %', p_new_status;
    END IF;

    SELECT status
    INTO v_old_status
    FROM scott.orders
    WHERE order_id = p_order_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order % not found', p_order_id;
    END IF;

    UPDATE scott.orders
    SET status = p_new_status
    WHERE order_id = p_order_id;

    RAISE NOTICE 'Order %: % -> %', p_order_id, v_old_status, p_new_status;
END;
$$;

-- Procedure 2: Dem khach hang theo quoc gia
CREATE OR REPLACE PROCEDURE scott.get_employee_count(
    IN p_country VARCHAR,
    INOUT p_count BIGINT,
    INOUT p_country_name VARCHAR
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT COUNT(*), COALESCE(MAX(c.country), 'Unknown')
    INTO p_count, p_country_name
    FROM scott.customers c
    WHERE UPPER(c.country) LIKE '%' || UPPER(p_country) || '%';
END;
$$;

-- ============================================================================
-- 6. TEST
-- ============================================================================

-- Test Functions
SELECT scott.get_customer_level(1) AS level;
SELECT scott.get_customer_level(3) AS level;
SELECT scott.calculate_order_total(1) AS total_order_1;
SELECT scott.calculate_order_total(4) AS total_order_4;

-- Test Procedures
DO $$
DECLARE
    v_count BIGINT := 0;
    v_country VARCHAR(50) := '';
BEGIN
    CALL scott.get_employee_count('Vietnam', v_count, v_country);
    RAISE NOTICE 'Country: %, Count: %', v_country, v_count;
END;
$$;

CALL scott.update_order_status(4, 'CONFIRMED');

-- Kiem tra Views
SELECT * FROM scott.v_customer_orders ORDER BY total_spent DESC;
SELECT * FROM scott.v_product_summary ORDER BY total_revenue DESC;

-- Kiem tra tables
SELECT COUNT(*) AS customers FROM scott.customers;
SELECT COUNT(*) AS products  FROM scott.products;
SELECT COUNT(*) AS orders    FROM scott.orders;
SELECT COUNT(*) AS items     FROM scott.order_items;
