-- ============================================================================
-- Script tao du lieu test cho Oracle Database (XEPDB1)
-- Schema: SCOTT
-- ============================================================================

-- Xoa objects cu (neu co)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE scott.order_items PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE scott.orders PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE scott.products PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE scott.customers PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW scott.v_customer_orders';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW scott.v_product_summary';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE scott.get_employee_count';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE scott.update_order_status';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION scott.calculate_order_total';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION scott.get_customer_level';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================================
-- 1. TABLES
-- ============================================================================

CREATE TABLE scott.customers (
    customer_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100) NOT NULL,
    email         VARCHAR2(150),
    city          VARCHAR2(50),
    country       VARCHAR2(50) DEFAULT 'Vietnam',
    created_at    DATE DEFAULT SYSDATE,
    status        VARCHAR2(20) DEFAULT 'ACTIVE'
);

CREATE TABLE scott.products (
    product_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(200) NOT NULL,
    category     VARCHAR2(50),
    price        NUMBER(12, 2) NOT NULL,
    stock        NUMBER(10) DEFAULT 0,
    created_at   DATE DEFAULT SYSDATE
);

CREATE TABLE scott.orders (
    order_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  NUMBER(10) NOT NULL,
    order_date   DATE DEFAULT SYSDATE,
    total_amount NUMBER(14, 2) DEFAULT 0,
    status       VARCHAR2(30) DEFAULT 'PENDING',
    shipping_city VARCHAR2(50)
);

CREATE TABLE scott.order_items (
    item_id       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     NUMBER(10) NOT NULL,
    product_id   NUMBER(10) NOT NULL,
    quantity     NUMBER(5) NOT NULL,
    unit_price   NUMBER(12, 2) NOT NULL,
    discount_pct NUMBER(5, 2) DEFAULT 0
);

-- Foreign Keys
ALTER TABLE scott.orders
    ADD CONSTRAINT fk_orders_customer
    FOREIGN KEY (customer_id) REFERENCES scott.customers(customer_id);

ALTER TABLE scott.order_items
    ADD CONSTRAINT fk_items_order
    FOREIGN KEY (order_id) REFERENCES scott.orders(order_id);

ALTER TABLE scott.order_items
    ADD CONSTRAINT fk_items_product
    FOREIGN KEY (product_id) REFERENCES scott.products(product_id);

-- ============================================================================
-- 2. DATA MAU
-- ============================================================================

-- Customers
INSERT INTO scott.customers (customer_name, email, city, country, status) VALUES ('Nguyen Van A', 'a.nguyen@email.com', 'Ho Chi Minh', 'Vietnam', 'ACTIVE');
INSERT INTO scott.customers (customer_name, email, city, country, status) VALUES ('Tran Thi B',   'b.tran@email.com',  'Ha Noi',     'Vietnam', 'ACTIVE');
INSERT INTO scott.customers (customer_name, email, city, country, status) VALUES ('Le Van C',     'c.le@email.com',    'Da Nang',    'Vietnam', 'INACTIVE');
INSERT INTO scott.customers (customer_name, email, city, country, status) VALUES ('Pham Thi D',   'd.pham@email.com',  'Can Tho',    'Vietnam', 'ACTIVE');
INSERT INTO scott.customers (customer_name, email, city, country, status) VALUES ('Hoang Van E',  'e.hoang@email.com', 'Hue',        'Vietnam', 'SUSPENDED');

-- Products
INSERT INTO scott.products (product_name, category, price, stock) VALUES ('Laptop Dell XPS 15',  'Electronics', 35000000, 25);
INSERT INTO scott.products (product_name, category, price, stock) VALUES ('iPhone 15 Pro',        'Electronics', 28000000, 50);
INSERT INTO scott.products (product_name, category, price, stock) VALUES ('Samsung Galaxy S24',   'Electronics', 22000000, 40);
INSERT INTO scott.products (product_name, category, price, stock) VALUES ('iPad Air M2',          'Electronics', 15000000, 30);
INSERT INTO scott.products (product_name, category, price, stock) VALUES ('MacBook Pro 14',       'Electronics', 42000000, 15);
INSERT INTO scott.products (product_name, category, price, stock) VALUES ('Sony WH-1000XM5',      'Accessories',  8500000, 60);
INSERT INTO scott.products (product_name, category, price, stock) VALUES ('AirPods Pro 2',        'Accessories',  5500000, 80);
INSERT INTO scott.products (product_name, category, price, stock) VALUES ('Apple Watch Ultra 2', 'Accessories', 18500000, 20);

-- Orders
INSERT INTO scott.orders (customer_id, order_date, total_amount, status, shipping_city) VALUES (1, SYSDATE - 10, 63000000, 'DELIVERED', 'Ho Chi Minh');
INSERT INTO scott.orders (customer_id, order_date, total_amount, status, shipping_city) VALUES (2, SYSDATE - 7,  35000000, 'SHIPPED',   'Ha Noi');
INSERT INTO scott.orders (customer_id, order_date, total_amount, status, shipping_city) VALUES (1, SYSDATE - 3,  15000000, 'CONFIRMED', 'Ho Chi Minh');
INSERT INTO scott.orders (customer_id, order_date, total_amount, status, shipping_city) VALUES (4, SYSDATE - 1,  28000000, 'PENDING',   'Can Tho');
INSERT INTO scott.orders (customer_id, order_date, total_amount, status, shipping_city) VALUES (2, SYSDATE,       22000000, 'PENDING',   'Ha Noi');

-- Order Items
INSERT INTO scott.order_items (order_id, product_id, quantity, unit_price, discount_pct) VALUES (1, 1, 1, 35000000,  0);
INSERT INTO scott.order_items (order_id, product_id, quantity, unit_price, discount_pct) VALUES (1, 6, 1,  8500000,  5);
INSERT INTO scott.order_items (order_id, product_id, quantity, unit_price, discount_pct) VALUES (1, 7, 2,  5500000,  0);
INSERT INTO scott.order_items (order_id, product_id, quantity, unit_price, discount_pct) VALUES (2, 2, 1, 28000000, 10);
INSERT INTO scott.order_items (order_id, product_id, quantity, unit_price, discount_pct) VALUES (3, 4, 1, 15000000,  0);
INSERT INTO scott.order_items (order_id, product_id, quantity, unit_price, discount_pct) VALUES (4, 3, 1, 22000000,  0);
INSERT INTO scott.order_items (order_id, product_id, quantity, unit_price, discount_pct) VALUES (5, 5, 1, 42000000,  0);

-- Update total_amount
UPDATE scott.orders SET total_amount = (
    SELECT NVL(SUM(quantity * unit_price * (1 - NVL(discount_pct, 0) / 100)), 0)
    FROM scott.order_items
    WHERE order_items.order_id = orders.order_id
);

COMMIT;

-- ============================================================================
-- 3. VIEWS
-- ============================================================================

-- View 1: Thong tin khach hang + so don hang + tong tien
CREATE OR REPLACE VIEW scott.v_customer_orders AS
SELECT
    c.customer_id,
    c.customer_name,
    c.city,
    c.country,
    c.status,
    COUNT(o.order_id)                        AS total_orders,
    NVL(SUM(o.total_amount), 0)              AS total_spent,
    NVL(AVG(o.total_amount), 0)              AS avg_order_value,
    NVL(MAX(o.total_amount), 0)              AS max_order_value
FROM scott.customers c
    LEFT JOIN scott.orders o ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id, c.customer_name, c.city, c.country, c.status;

-- View 2: Tom tat san pham + doanh thu + ton kho
CREATE OR REPLACE VIEW scott.v_product_summary AS
SELECT
    p.product_id,
    p.product_name,
    p.category,
    p.price,
    p.stock,
    NVL(SUM(oi.quantity), 0) AS total_sold,
    NVL(SUM(oi.quantity * oi.unit_price * (1 - NVL(oi.discount_pct, 0) / 100)), 0) AS total_revenue
FROM scott.products p
    LEFT JOIN scott.order_items oi ON p.product_id = oi.product_id
    LEFT JOIN scott.orders o ON oi.order_id = o.order_id
GROUP BY
    p.product_id, p.product_name, p.category, p.price, p.stock;

-- ============================================================================
-- 4. FUNCTIONS
-- ============================================================================

-- Function 1: Tinh cap bac khach hang
CREATE OR REPLACE FUNCTION scott.get_customer_level(p_customer_id IN NUMBER)
RETURN VARCHAR2
IS
    v_total NUMBER;
    v_level VARCHAR2(20);
BEGIN
    SELECT NVL(SUM(total_amount), 0)
    INTO v_total
    FROM scott.orders
    WHERE customer_id = p_customer_id AND status != 'CANCELLED';

    IF v_total >= 50000000 THEN
        v_level := 'GOLD';
    ELSIF v_total >= 20000000 THEN
        v_level := 'SILVER';
    ELSIF v_total >= 5000000 THEN
        v_level := 'BRONZE';
    ELSE
        v_level := 'NEW';
    END IF;

    RETURN v_level;
END;
/

-- Function 2: Tinh tong tien don hang (co discount)
CREATE OR REPLACE FUNCTION scott.calculate_order_total(p_order_id IN NUMBER)
RETURN NUMBER
IS
    v_total NUMBER := 0;
BEGIN
    SELECT NVL(SUM(quantity * unit_price * (1 - NVL(discount_pct, 0) / 100)), 0)
    INTO v_total
    FROM scott.order_items
    WHERE order_id = p_order_id;

    RETURN ROUND(v_total, 2);
END;
/

-- ============================================================================
-- 5. PROCEDURES
-- ============================================================================

-- Procedure 1: Cap nhat trang thai don hang
CREATE OR REPLACE PROCEDURE scott.update_order_status(
    p_order_id   IN NUMBER,
    p_new_status IN VARCHAR2
)
IS
    v_old_status VARCHAR2(30);
BEGIN
    IF p_new_status NOT IN ('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED') THEN
        RAISE_APPLICATION_ERROR(-20001, 'Invalid status: ' || p_new_status);
    END IF;

    SELECT status INTO v_old_status FROM scott.orders WHERE order_id = p_order_id;

    UPDATE scott.orders
    SET status = p_new_status
    WHERE order_id = p_order_id;

    DBMS_OUTPUT.PUT_LINE('Order ' || p_order_id || ': ' || v_old_status || ' -> ' || p_new_status);
END;
/

-- Procedure 2: Dem khach hang theo quoc gia
CREATE OR REPLACE PROCEDURE scott.get_employee_count(
    p_country       IN  VARCHAR2,
    p_count         OUT NUMBER,
    p_country_name  OUT VARCHAR2
)
IS
BEGIN
    SELECT COUNT(*), NVL(MAX(c.country), 'Unknown')
    INTO p_count, p_country_name
    FROM scott.customers c
    WHERE UPPER(c.country) LIKE '%' || UPPER(p_country) || '%';
END;
/

-- ============================================================================
-- 6. TEST
-- ============================================================================

-- Test Functions
SELECT scott.get_customer_level(1) AS level FROM DUAL;
SELECT scott.get_customer_level(3) AS level FROM DUAL;
SELECT scott.calculate_order_total(1) AS total_order_1 FROM DUAL;
SELECT scott.calculate_order_total(4) AS total_order_4 FROM DUAL;

-- Test Procedures
DECLARE
    v_count NUMBER;
    v_country VARCHAR2(50);
BEGIN
    scott.get_employee_count('Vietnam', v_count, v_country);
    DBMS_OUTPUT.PUT_LINE('Country: ' || v_country || ', Count: ' || v_count);
END;
/

BEGIN
    scott.update_order_status(4, 'CONFIRMED');
END;
/

-- Kiem tra Views
SELECT * FROM scott.v_customer_orders ORDER BY total_spent DESC;
SELECT * FROM scott.v_product_summary ORDER BY total_revenue DESC;

-- Kiem tra tables
SELECT COUNT(*) AS customers FROM scott.customers;
SELECT COUNT(*) AS products  FROM scott.products;
SELECT COUNT(*) AS orders    FROM scott.orders;
SELECT COUNT(*) AS items    FROM scott.order_items;

COMMIT;
